import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/theme/themeProvider.ts",
  ],
  theme: {
    extend: {
      boxShadow: {
        custom: "-3px 8px 55px 16px rgba(0, 0, 0, 0.14)",
        shadow_primary: "shadow-custom",
        shadow_green: "0 4px 6px -1px #80F8BF",
        shadow_success: "0 4px 6px -1px rgba(255, 141, 42, 1)",
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        text_black: "#000000",
        text_white: "#FFFFFF",
        text_gray: "#919191",
        text_lightGray: "#CECECE",
        text_error: "#F1866F",
        text_middleGray: "#ADADAD",
        text_success: "#80F8BF",
        text_mainGray: "#B2B3B6",
        primary_dark: "#0F0F0F",
        primary_white: "#FFFFFF",
        accent_primary: "#FF8D2A",
        accent_secondary: "#FFBF88",
        gradients_primary: "bg-gradientPrimary",
        gradients_secondary: "bg-gradientSecondary",
        icons_white: "#FFFFFF",
        icons_dark: "#0F0F0F",
        icons_gray: "#919191",
        icons_lightGray: "#CECECE",
        icons_mainBtn: "#FF8D2A",
        icons_lightBlue: "#18A0FB",
        icons_error: "#F1866F",
        icons_darkGreen: "#26A17B",
        icons_lightGreen: "#80F8BF",
        icons_middleGray: "#B2B3B6",
        icons_secondGray: "#C8C8C8",
        icons_yellow: "#DFD600",
        icons_middleBlue: "#0081DF",
        icons_success: "#00DF59",
        icons_orange: "#DF7800",
        icons_lightYellow: "#E2E701",
        icons_turquoise: "#00E6F5",
        icons_blue: "#0036F5",
        icons_darkGray: "#919191",
        secondary_dark: "#262525",
        secondary_black: "#212121",
        secondary_lightBlue: "#799FFF",
        secondary_violet: "#AB93CB",
        secondary_lightGray: "#CADDE4",
        secondary_beige: "#FFBF88",
        secondary_main: "#1E2128",
        secondary_second: "#2D323D",
        secondary_gray: "#C8C8C8",
        secondary_shadowGray: "#4F4F4F",
      },
      spacing: {
        "leading-140": "140%",
      },
      letterSpacing: {
        "-4": "-0.04em",
      },
      backgroundImage: {
        gradientPrimary:
          "linear-gradient(180deg, rgba(0, 0, 0, 0.52) 0%, rgba(0, 0, 0, 0) 100%)",
        gradientSecondary:
          "radial-gradient(50% 50% at 50% 50%, #FF8D2A 0%, rgba(217, 217, 217, 0) 100%)",
      },
    },
  },
  plugins: [],
} satisfies Config;
